#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Write the grid generated by island_alinged_grid.py or one_zone_grid.py in the
EMC3-EIRENE format.

Input parameters are read from input_params.dat (through input_params.py):
flag_type_init selects the grid type, 3 for the island aligned grid (core, the m
islands and the PFR as separate zones) and 4 for the one zone grid, and path is
the suffix of the pickle files written by the grid scripts to the output
directory.

Files written to the output directory:

    grid3D.dat          grid coordinates of all zones (cm and degrees)
    bfield.dat          magnetic field strength at the grid points of all zones (T)
    resolution7z.dat    radial, poloidal and toroidal number of points of the core,
    or resolution1z.dat island and PFR zones (7 zones), or of the single zone

The resolution file is the input of make_input_geo_n0g.py.

In grid3D.dat every zone starts with a line with its number of radial, poloidal
and toroidal points, followed for every toroidal plane by the toroidal angle, all
R values and all Z values, four per line and with the radial index running
fastest. bfield.dat holds the field strength at the same points in the same
order, without any header lines.

Usage, from the repository root where input_params.dat is:
    python emc3_eirene_input/write_emc3_grid.py [output_dir]

Defaults:
    output_dir = output
"""
import os
import pickle
import sys

import numpy as np

# input_params lives in the repository root, one level up
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import input_params as ip

M_TO_CM = 100.0
VALUES_PER_LINE = 4


def load_pickle(file_path):
    """Load one of the pickled grid lists as an array (n_tor, n_pol, n_rad)."""
    with open(file_path, 'rb') as file:
        return np.array(pickle.load(file))


def load_zone(output_dir, name, prefix_r, prefix_z, prefix_b):
    """Load R, Z and B of one zone. B is None if it was not stored."""
    zone = {'name': name,
            'R': load_pickle(os.path.join(output_dir, f"{prefix_r}{ip.path}.pkl")),
            'Z': load_pickle(os.path.join(output_dir, f"{prefix_z}{ip.path}.pkl"))}

    file_path_b = os.path.join(output_dir, f"{prefix_b}{ip.path}.pkl")
    zone['B'] = load_pickle(file_path_b) if os.path.exists(file_path_b) else None
    return zone


def load_one_zone_grid(output_dir='output'):
    """The one zone grid written by one_zone_grid.py, as a list of one zone."""
    return [load_zone(output_dir, 'one zone', 'R', 'Z', 'B')]


def load_island_aligned_grid(output_dir='output'):
    """The island aligned grid written by island_alinged_grid.py.

    Zone order: core, the m islands, PFR. The island arrays are flipped in the
    poloidal and the radial direction so that all zones have the same
    orientation.
    """
    zones = [load_zone(output_dir, 'core', 'R_lines_theta_r_core',
                       'Z_lines_theta_r_core', 'B_lines_theta_r_core')]

    for m_period in range(ip.m):
        zone = load_zone(output_dir, f'island {m_period}',
                         f'R_lines_theta_r_island_{m_period}',
                         f'Z_lines_theta_r_island_{m_period}',
                         f'B_lines_theta_r_island_{m_period}')
        for key in ('R', 'Z', 'B'):
            if zone[key] is not None:
                zone[key] = np.flip(zone[key], axis=(1, 2))
        zones.append(zone)

    zones.append(load_zone(output_dir, 'pfr', 'R_lines_theta_r_pfr',
                           'Z_lines_theta_r_pfr', 'B_lines_theta_r_pfr'))
    return zones


def load_grid(output_dir='output'):
    """The grid selected by flag_type_init."""
    if ip.flag_type_init == 3:
        return load_island_aligned_grid(output_dir)
    if ip.flag_type_init == 4:
        return load_one_zone_grid(output_dir)
    raise ValueError(f"flag_type_init = {ip.flag_type_init}: only 3 (island aligned grid) "
                     f"and 4 (one zone grid) can be written for EMC3-EIRENE.")


def resolution(zone):
    """Number of radial, poloidal and toroidal points of a zone."""
    n_tor, n_pol, n_rad = zone['R'].shape
    return n_rad, n_pol, n_tor


def write_values(file, values):
    """Write a flat sequence of values, VALUES_PER_LINE per line."""
    values = np.ravel(values)
    for i_start in range(0, len(values), VALUES_PER_LINE):
        file.write(''.join(f"  {value}" for value in values[i_start:i_start + VALUES_PER_LINE]))
        file.write('\n')


def write_grid3d(zones, file_path):
    """Write the grid coordinates of all zones (cm and degrees)."""
    with open(file_path, 'w') as file:
        for zone in zones:
            n_rad, n_pol, n_tor = resolution(zone)
            file.write(f" {n_rad} {n_pol} {n_tor}\n")
            for i_tor in range(n_tor):
                phi = i_tor * (360.0 / ip.nfp) / (n_tor - 1) if n_tor > 1 else 0.0
                file.write(f" {phi}\n")
                write_values(file, zone['R'][i_tor] * M_TO_CM)
                write_values(file, zone['Z'][i_tor] * M_TO_CM)


def write_bfield(zones, file_path):
    """Write the magnetic field strength at the grid points of all zones (T).

    A zone without stored field gets the uniform field B_0.
    """
    with open(file_path, 'w') as file:
        for zone in zones:
            if zone['B'] is None:
                print(f"Warning: no magnetic field stored for the zone '{zone['name']}', "
                      f"writing the uniform field B_0 = {ip.B_0} T")
                B = np.full(zone['R'].shape, float(ip.B_0))
            else:
                B = zone['B']
            for i_tor in range(B.shape[0]):
                write_values(file, B[i_tor])


def write_resolution(zones, file_path):
    """Write the resolution of the zone types, the input of make_input_geo_n0g.py.

    One zone: n_rad n_pol n_tor. Island aligned grid: the same three numbers for
    the core, for an island and for the PFR.
    """
    if len(zones) == 1:
        selected = zones
    else:
        selected = [zones[0], zones[1], zones[-1]]

    with open(file_path, 'w') as file:
        file.write(' '.join(str(n) for zone in selected for n in resolution(zone)))


def resolution_file_name(zones):
    """resolution1z.dat for the one zone grid, resolution7z.dat otherwise."""
    return 'resolution1z.dat' if len(zones) == 1 else 'resolution7z.dat'


def write_emc3_files(zones, output_dir='output'):
    """Write grid3D.dat, bfield.dat and the resolution file. Returns their paths."""
    paths = [os.path.join(output_dir, name)
             for name in ('grid3D.dat', 'bfield.dat', resolution_file_name(zones))]
    write_grid3d(zones, paths[0])
    write_bfield(zones, paths[1])
    write_resolution(zones, paths[2])
    return paths


def main():
    output_dir = sys.argv[1] if len(sys.argv) > 1 else 'output'

    zones = load_grid(output_dir)
    for zone in zones:
        n_rad, n_pol, n_tor = resolution(zone)
        print(f"{zone['name']}: {n_rad} radial x {n_pol} poloidal x {n_tor} toroidal points"
              + ("" if zone['B'] is not None else " (no magnetic field stored)"))

    for path in write_emc3_files(zones, output_dir):
        print(f"written '{path}'")


if __name__ == '__main__':
    main()
